### ISSUE TITLE
dateRestrict parameter =>  Verification of string error

### ISSUE THREAD

**Issue by MatthewsMike** [manwar/WWW-Google-CustomSearch#2]
In your module you check for a valid entry for dateRestrict. 

You code is expecting the format of d[1] (i.e. search results from 1 day ago)
The proper format is just  d1

Line 176 of params.pm needs to be updated:
from
sub check_date_restrict { return ($_[0] =~ /^[d|w|m|y]**\[\d+\]**$/i) };
to
sub check_date_restrict { return ($_[0] =~ /^[d|w|m|y]**\d+**$/i) };

Thanks!

**Comment by manwar** [comment]
Hi @electromike 

Thanks for raising the issue.
It has now been addressed in WWW::Google::CustomSearch v0.33

Best Regards,
Mohammad S Anwar

**Comment by manwar** [comment]
Closing the issue as it has been resolved.
